services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rovibrational_cpp_dev
    volumes:
      - .:/workspace                # ホストのカレントディレクトリを /workspace にマウント
    working_dir: /workspace
    tty: true                       # コンテナ起動後にbashで操作できる
