[build-system]
requires = ["scikit-build-core", "pybind11", "cmake", "build"]
build-backend = "scikit_build_core.build"

[project]
name = "rvx"
version = "0.1.0"
description = "Fast Liouville-von Neumann propagator (C++/Eigen/OpenMP)"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
classifiers = ["Programming Language :: Python :: 3"]
